version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: data

  app:
    build: .
    ports:
      - "5000:5000"
    command: python3 app.py
    depends_on:
      - db